<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cities', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('state_id');
            $table->string('name');
            $table->softDeletes();
        });

        // DB::table('cities')->insert([
        //     //Ayeyarwady Division
        //     ['state_id' => '1', 'name' => 'Bogale'],
        //     ['state_id' => '1', 'name' => 'Danubyu'],
        //     ['state_id' => '1', 'name' => 'Dedaye'],
        //     ['state_id' => '1', 'name' => 'Einme'],
        //     ['state_id' => '1', 'name' => 'Hinthada'],
        //     ['state_id' => '1', 'name' => 'Ingapu'],
        //     ['state_id' => '1', 'name' => 'Kangyidaunt'],
        //     ['state_id' => '1', 'name' => 'Kyaiklat'],
        //     ['state_id' => '1', 'name' => 'Kyangin'],
        //     ['state_id' => '1', 'name' => 'Kyaunggon'],
        //     ['state_id' => '1', 'name' => 'Kyonpyaw'],
        //     ['state_id' => '1', 'name' => 'Labutta'],
        //     ['state_id' => '1', 'name' => 'Lemyethna'],
        //     ['state_id' => '1', 'name' => 'Maubin'],
        //     ['state_id' => '1', 'name' => 'Mawlamyinegyun'],
        //     ['state_id' => '1', 'name' => 'Myanaung'],
        //     ['state_id' => '1', 'name' => 'Myaungmya'],
        //     ['state_id' => '1', 'name' => 'Ngapudaw'],
        //     ['state_id' => '1', 'name' => 'Nyaungdon'],
        //     ['state_id' => '1', 'name' => 'Pantanaw'],
        //     ['state_id' => '1', 'name' => 'Pathein'],
        //     ['state_id' => '1', 'name' => 'Pyapon'],
        //     ['state_id' => '1', 'name' => 'Thabaung'],
        //     ['state_id' => '1', 'name' => 'Wakema'],
        //     ['state_id' => '1', 'name' => 'Yegyi'],
        //     ['state_id' => '1', 'name' => 'Zalun'],


        //     // Bago East Division
        //     ['state_id' => '2', 'name' => 'Bago'],
        //     ['state_id' => '2', 'name' => 'Daik-U'],
        //     ['state_id' => '2', 'name' => 'Kawa'],
        //     ['state_id' => '2', 'name' => 'Kyaukkyi'],
        //     ['state_id' => '2', 'name' => 'Kyauktaga'],
        //     ['state_id' => '2', 'name' => 'Nyaunglebin'],
        //     ['state_id' => '2', 'name' => 'Oktwin'],
        //     ['state_id' => '2', 'name' => 'Phyu'],
        //     ['state_id' => '2', 'name' => 'Shwegyin'],
        //     ['state_id' => '2', 'name' => 'Tantabin'],
        //     ['state_id' => '2', 'name' => 'Taungoo'],
        //     ['state_id' => '2', 'name' => 'Thanatpin'],
        //     ['state_id' => '2', 'name' => 'Waw'],
        //     ['state_id' => '2', 'name' => 'Yedashe'],
        //     ['state_id' => '2', 'name' => 'Gyobingauk'],
        //     ['state_id' => '2', 'name' => 'Letpadan'],
        //     ['state_id' => '2', 'name' => 'Minhla'],
        //     ['state_id' => '2', 'name' => 'Monyo'],
        //     ['state_id' => '2', 'name' => 'Nattalin'],
        //     ['state_id' => '2', 'name' => 'Okpho'],
        //     ['state_id' => '2', 'name' => 'Padaung'],
        //     ['state_id' => '2', 'name' => 'Pauk Kaung'],
        //     ['state_id' => '2', 'name' => 'Paungde'],
        //     ['state_id' => '2', 'name' => 'Pyay'],
        //     ['state_id' => '2', 'name' => 'Shwedaung'],
        //     ['state_id' => '2', 'name' => 'Thayarwady'],
        //     ['state_id' => '2', 'name' => 'Thegon'],
        //     ['state_id' => '2', 'name' => 'Zigon'],

        //     // Chin State
        //     ['state_id' => '3', 'name' => 'Falam'],
        //     ['state_id' => '3', 'name' => 'Hakha'],
        //     ['state_id' => '3', 'name' => 'Htantlang'],
        //     ['state_id' => '3', 'name' => 'Kanpetlet'],
        //     ['state_id' => '3', 'name' => 'Madupi'],
        //     ['state_id' => '3', 'name' => 'Mindat'],
        //     ['state_id' => '3', 'name' => 'Paletwa'],
        //     ['state_id' => '3', 'name' => 'Tiddim'],
        //     ['state_id' => '3', 'name' => 'Tonzang'],

        //     // Kachin State
        //     ['state_id' => '4', 'name' => 'Bhamo'],
        //     ['state_id' => '4', 'name' => 'Chipwi'],
        //     ['state_id' => '4', 'name' => 'Hpakan'],
        //     ['state_id' => '4', 'name' => 'Injangyang'],
        //     ['state_id' => '4', 'name' => 'Kawnglanghpu'],
        //     ['state_id' => '4', 'name' => 'Machanbaw'],
        //     ['state_id' => '4', 'name' => 'Mansi'],
        //     ['state_id' => '4', 'name' => 'Mogaung'],
        //     ['state_id' => '4', 'name' => 'Mohnyin'],
        //     ['state_id' => '4', 'name' => 'Momauk'],
        //     ['state_id' => '4', 'name' => 'Myitkyina'],
        //     ['state_id' => '4', 'name' => 'Nogmung'],
        //     ['state_id' => '4', 'name' => 'Puta-O'],
        //     ['state_id' => '4', 'name' => 'Shwegu'],
        //     ['state_id' => '4', 'name' => 'Sumprabum'],
        //     ['state_id' => '4', 'name' => 'Tanai'],
        //     ['state_id' => '4', 'name' => 'Tsawlaw'],
        //     ['state_id' => '4', 'name' => 'Waingmaw'],

        //     // Kayah State
        //     ['state_id' => '5', 'name' => 'Bawlakhe'],
        //     ['state_id' => '5', 'name' => 'Demoso'],
        //     ['state_id' => '5', 'name' => 'Hpasawng'],
        //     ['state_id' => '5', 'name' => 'Hpruso'],
        //     ['state_id' => '5', 'name' => 'Loikaw'],
        //     ['state_id' => '5', 'name' => 'Mese'],
        //     ['state_id' => '5', 'name' => 'Shadaw'],

        //     // Kayin State
        //     ['state_id' => '6', 'name' => 'Hlaingbwe'],
        //     ['state_id' => '6', 'name' => 'Hpa-An'],
        //     ['state_id' => '6', 'name' => 'Hpapun'],
        //     ['state_id' => '6', 'name' => 'Kawkareik'],
        //     ['state_id' => '6', 'name' => 'Kyain Seikgyi'],
        //     ['state_id' => '6', 'name' => 'Myawaddy'],
        //     ['state_id' => '6', 'name' => 'Thandaung'],

        //     // Magway Division
        //     ['state_id' => '7', 'name' => 'Aunglan'],
        //     ['state_id' => '7', 'name' => 'Chauk'],
        //     ['state_id' => '7', 'name' => 'Gangaw'],
        //     ['state_id' => '7', 'name' => 'Kamma'],
        //     ['state_id' => '7', 'name' => 'Magway'],
        //     ['state_id' => '7', 'name' => 'Minbu'],
        //     ['state_id' => '7', 'name' => 'Mindon'],
        //     ['state_id' => '7', 'name' => 'Minhla'],
        //     ['state_id' => '7', 'name' => 'Myaing'],
        //     ['state_id' => '7', 'name' => 'Myothit'],
        //     ['state_id' => '7', 'name' => 'Natmauk'],
        //     ['state_id' => '7', 'name' => 'Ngape'],
        //     ['state_id' => '7', 'name' => 'Pakokku'],
        //     ['state_id' => '7', 'name' => 'Pauk'],
        //     ['state_id' => '7', 'name' => 'Pwintbyu'],
        //     ['state_id' => '7', 'name' => 'Salin'],
        //     ['state_id' => '7', 'name' => 'Saw'],
        //     ['state_id' => '7', 'name' => 'Seikphyu'],
        //     ['state_id' => '7', 'name' => 'Sidoktaya'],
        //     ['state_id' => '7', 'name' => 'Sinbaungwe'],
        //     ['state_id' => '7', 'name' => 'Taungdwingyi'],
        //     ['state_id' => '7', 'name' => 'Thayet'],
        //     ['state_id' => '7', 'name' => 'Tilin'],
        //     ['state_id' => '7', 'name' => 'Yenangyaung'],
        //     ['state_id' => '7', 'name' => 'Yesagyo'],

        //     // Mandalay Division
        //     ['state_id' => '8', 'name' => 'Amarapura'],
        //     ['state_id' => '8', 'name' => 'Aungmyaythazan'],
        //     ['state_id' => '8', 'name' => 'Chanayethazan'],
        //     ['state_id' => '8', 'name' => 'Chanmyathazi'],
        //     ['state_id' => '8', 'name' => 'Kyaukpadaung'],
        //     ['state_id' => '8', 'name' => 'Kyaukse'],
        //     ['state_id' => '8', 'name' => 'Lewe'],
        //     ['state_id' => '8', 'name' => 'Madaya'],
        //     ['state_id' => '8', 'name' => 'Mahaaungmyay'],
        //     ['state_id' => '8', 'name' => 'Mahlaing'],
        //     ['state_id' => '8', 'name' => 'Mandalay'],
        //     ['state_id' => '8', 'name' => 'Meiktila'],
        //     ['state_id' => '8', 'name' => 'Mogoke'],
        //     ['state_id' => '8', 'name' => 'Myingyan'],
        //     ['state_id' => '8', 'name' => 'Myittha'],
        //     ['state_id' => '8', 'name' => 'Natogyi'],
        //     ['state_id' => '8', 'name' => 'Ngazun'],
        //     ['state_id' => '8', 'name' => 'Nyaung-U'],
        //     ['state_id' => '8', 'name' => 'Patheingyi'],
        //     ['state_id' => '8', 'name' => 'Pyawbwe'],
        //     ['state_id' => '8', 'name' => 'Pyigyitagon'],
        //     ['state_id' => '8', 'name' => 'Pyinmana'],
        //     ['state_id' => '8', 'name' => 'Pyinoolwin'],
        //     ['state_id' => '8', 'name' => 'Singu'],
        //     ['state_id' => '8', 'name' => 'Sintgaing'],
        //     ['state_id' => '8', 'name' => 'Tada-U'],
        //     ['state_id' => '8', 'name' => 'Tatkon'],
        //     ['state_id' => '8', 'name' => 'Taungtha'],
        //     ['state_id' => '8', 'name' => 'Thabeikkyin'],
        //     ['state_id' => '8', 'name' => 'Thazi'],
        //     ['state_id' => '8', 'name' => 'Wundwin'],
        //     ['state_id' => '8', 'name' => 'Yamethin'],

        //     // Mon State
        //     ['state_id' => '9', 'name' => 'Bilin'],
        //     ['state_id' => '9', 'name' => 'Chaungzon'],
        //     ['state_id' => '9', 'name' => 'Kyaikmaraw'],
        //     ['state_id' => '9', 'name' => 'Kyaikto'],
        //     ['state_id' => '9', 'name' => 'Mawlamyine'],
        //     ['state_id' => '9', 'name' => 'Mudon'],
        //     ['state_id' => '9', 'name' => 'Paung'],
        //     ['state_id' => '9', 'name' => 'Thanbyuzayat'],
        //     ['state_id' => '9', 'name' => 'Thaton'],
        //     ['state_id' => '9', 'name' => 'Ye'],

        //     /* Naypitaw U.Territory Region */
        //     ['state_id' => '10', 'name' => 'Dhatkhina Thiri'],
        //     ['state_id' => '10', 'name' => 'Lae way'],
        //     ['state_id' => '10', 'name' => 'Ottara Thiri'],
        //     ['state_id' => '10', 'name' => 'Pobba Thiri'],
        //     ['state_id' => '10', 'name' => 'Pyinmana'],
        //     ['state_id' => '10', 'name' => 'Tatkon'],
        //     ['state_id' => '10', 'name' => 'Yamethin'],
        //     ['state_id' => '10', 'name' => 'Zabuthiri'],
        //     ['state_id' => '10', 'name' => 'Zayar Thiri'],

        //     /* Rakhine State */
        //     ['state_id' => '11', 'name' => 'Ann'],
        //     ['state_id' => '11', 'name' => 'Buthidaung'],
        //     ['state_id' => '11', 'name' => 'Gwa'],
        //     ['state_id' => '11', 'name' => 'Kyaukpyu'],
        //     ['state_id' => '11', 'name' => 'Kyauktaw'],
        //     ['state_id' => '11', 'name' => 'Maungdaw'],
        //     ['state_id' => '11', 'name' => 'Minbya'],
        //     ['state_id' => '11', 'name' => 'Mrauk-U'],
        //     ['state_id' => '11', 'name' => 'Munaung'],
        //     ['state_id' => '11', 'name' => 'Myebon'],
        //     ['state_id' => '11', 'name' => 'Pauktaw'],
        //     ['state_id' => '11', 'name' => 'Ponnagyun'],
        //     ['state_id' => '11', 'name' => 'Ramree'],
        //     ['state_id' => '11', 'name' => 'Rathedaung'],
        //     ['state_id' => '11', 'name' => 'Sittwe'],
        //     ['state_id' => '11', 'name' => 'Thandwe'],
        //     ['state_id' => '11', 'name' => 'Toungup'],

        //     // Sagaing Division
        //     ['state_id' => '12', 'name' => 'Ayadaw'],
        //     ['state_id' => '12', 'name' => 'Banmauk'],
        //     ['state_id' => '12', 'name' => 'Budalin'],
        //     ['state_id' => '12', 'name' => 'Chaung-U'],
        //     ['state_id' => '12', 'name' => 'Hkamti'],
        //     ['state_id' => '12', 'name' => 'Homalin'],
        //     ['state_id' => '12', 'name' => 'Indaw'],
        //     ['state_id' => '12', 'name' => 'Kale'],
        //     ['state_id' => '12', 'name' => 'Kalewa'],
        //     ['state_id' => '12', 'name' => 'kanbalu'],
        //     ['state_id' => '12', 'name' => 'Kani'],
        //     ['state_id' => '12', 'name' => 'Katha'],
        //     ['state_id' => '12', 'name' => 'Kawlin'],
        //     ['state_id' => '12', 'name' => 'Khin-U'],
        //     ['state_id' => '12', 'name' => 'Kyunhla'],
        //     ['state_id' => '12', 'name' => 'Lahe'],
        //     ['state_id' => '12', 'name' => 'Lay Shi'],
        //     ['state_id' => '12', 'name' => 'Mawlaik'],
        //     ['state_id' => '12', 'name' => 'Mingin'],
        //     ['state_id' => '12', 'name' => 'Monywa'],
        //     ['state_id' => '12', 'name' => 'Myaung'],
        //     ['state_id' => '12', 'name' => 'Myinmu'],
        //     ['state_id' => '12', 'name' => 'Nanyun'],
        //     ['state_id' => '12', 'name' => 'Pale'],
        //     ['state_id' => '12', 'name' => 'Paungbyin'],
        //     ['state_id' => '12', 'name' => 'Pinlebu'],
        //     ['state_id' => '12', 'name' => 'Sagaing'],
        //     ['state_id' => '12', 'name' => 'Salingyi'],
        //     ['state_id' => '12', 'name' => 'Shwebo'],
        //     ['state_id' => '12', 'name' => 'Tabayin'],
        //     ['state_id' => '12', 'name' => 'Tamu'],
        //     ['state_id' => '12', 'name' => 'Taze'],
        //     ['state_id' => '12', 'name' => 'Tigyaing'],
        //     ['state_id' => '12', 'name' => 'Wetlet'],
        //     ['state_id' => '12', 'name' => 'Wuntho'],
        //     ['state_id' => '12', 'name' => 'Ye-U'],
        //     ['state_id' => '12', 'name' => 'Yinmabin'],

        //     // Shan State (East)
        //     ['state_id' => '13', 'name' => 'Kengtung'],
        //     ['state_id' => '13', 'name' => 'Matman'],
        //     ['state_id' => '13', 'name' => 'Monghpyak'],
        //     ['state_id' => '13', 'name' => 'Monghsat'],
        //     ['state_id' => '13', 'name' => 'Mongkhet'],
        //     ['state_id' => '13', 'name' => 'Mongla'],
        //     ['state_id' => '13', 'name' => 'Mongping'],
        //     ['state_id' => '13', 'name' => 'Mongton'],
        //     ['state_id' => '13', 'name' => 'Mongyang'],
        //     ['state_id' => '13', 'name' => 'Mongyawng'],
        //     ['state_id' => '13', 'name' => 'Tachileik'],

        //     // Shan State (North)
        //     ['state_id' => '14', 'name' => 'Hopang'],
        //     ['state_id' => '14', 'name' => 'Hseni'],
        //     ['state_id' => '14', 'name' => 'Hsipaw'],
        //     ['state_id' => '14', 'name' => 'Konkyan'],
        //     ['state_id' => '14', 'name' => 'Kunlong'],
        //     ['state_id' => '14', 'name' => 'Kutkai'],
        //     ['state_id' => '14', 'name' => 'Kyuakme'],
        //     ['state_id' => '14', 'name' => 'Lashio'],
        //     ['state_id' => '14', 'name' => 'Laukkaing'],
        //     ['state_id' => '14', 'name' => 'Mabein'],
        //     ['state_id' => '14', 'name' => 'Manton'],
        //     ['state_id' => '14', 'name' => 'Mongmao'],
        //     ['state_id' => '14', 'name' => 'Mongmit'],
        //     ['state_id' => '14', 'name' => 'Mongyai'],
        //     ['state_id' => '14', 'name' => 'Muse'],
        //     ['state_id' => '14', 'name' => 'Namhsan'],
        //     ['state_id' => '14', 'name' => 'Namphan'],
        //     ['state_id' => '14', 'name' => 'Namtu'],
        //     ['state_id' => '14', 'name' => 'Nanhkan'],
        //     ['state_id' => '14', 'name' => 'Nawnghkio'],
        //     ['state_id' => '14', 'name' => 'Pangsang'],
        //     ['state_id' => '14', 'name' => 'Pangwaun'],
        //     ['state_id' => '14', 'name' => 'Tangyan'],

        //     // Shan State (South)
        //     ['state_id' => '15', 'name' => 'Hopong'],
        //     ['state_id' => '15', 'name' => 'Hsihseng'],
        //     ['state_id' => '15', 'name' => 'Kalaw'],
        //     ['state_id' => '15', 'name' => 'Kunhing'],
        //     ['state_id' => '15', 'name' => 'Kyethi'],
        //     ['state_id' => '15', 'name' => 'Laihka'],
        //     ['state_id' => '15', 'name' => 'Langkho'],
        //     ['state_id' => '15', 'name' => 'Lawksawk'],
        //     ['state_id' => '15', 'name' => 'Loilen'],
        //     ['state_id' => '15', 'name' => 'Mawkmai'],
        //     ['state_id' => '15', 'name' => 'Monghsu'],
        //     ['state_id' => '15', 'name' => 'Mongkaung'],
        //     ['state_id' => '15', 'name' => 'Mongnai'],
        //     ['state_id' => '15', 'name' => 'Mongpan'],
        //     ['state_id' => '15', 'name' => 'Nansang'],
        //     ['state_id' => '15', 'name' => 'Nyaungshwe'],
        //     ['state_id' => '15', 'name' => 'Pekon'],
        //     ['state_id' => '15', 'name' => 'Pindaya'],
        //     ['state_id' => '15', 'name' => 'Pinlaung'],
        //     ['state_id' => '15', 'name' => 'Taunggyi'],
        //     ['state_id' => '15', 'name' => 'Ywangan'],

        //     // Tanintharyi Division
        //     ['state_id' => '16', 'name' => 'Bokpyin'],
        //     ['state_id' => '16', 'name' => 'Dawei'],
        //     ['state_id' => '16', 'name' => 'Kawthoung'],
        //     ['state_id' => '16', 'name' => 'Kyunsu'],
        //     ['state_id' => '16', 'name' => 'Launglon'],
        //     ['state_id' => '16', 'name' => 'Myeik'],
        //     ['state_id' => '16', 'name' => 'Palaw'],
        //     ['state_id' => '16', 'name' => 'Tanintharyi'],
        //     ['state_id' => '16', 'name' => 'Thayetchaung'],
        //     ['state_id' => '16', 'name' => 'Yebyu'],

        //     ['state_id' => '17', 'name' => 'Dagon Myothit'],
        //     ['state_id' => '17', 'name' => 'Yangon City'],
        //     ['state_id' => '17', 'name' => 'Yangon Division'],
        // ]);

        // DB::table('cities')->insert([
        //     //Ayeyarwady Division
        //     ['state_id' => 'MMS01', 'id' => 'MMC001', 'name' => 'Bogale'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC002', 'name' => 'Danubyu'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC003', 'name' => 'Dedaye'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC004', 'name' => 'Einme'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC005', 'name' => 'Hinthada'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC006', 'name' => 'Ingapu'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC007', 'name' => 'Kangyidaunt'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC008', 'name' => 'Kyaiklat'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC009', 'name' => 'Kyangin'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC010', 'name' => 'Kyaunggon'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC011', 'name' => 'Kyonpyaw'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC012', 'name' => 'Labutta'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC013', 'name' => 'Lemyethna'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC014', 'name' => 'Maubin'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC015', 'name' => 'Mawlamyinegyun'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC016', 'name' => 'Myanaung'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC017', 'name' => 'Myaungmya'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC018', 'name' => 'Ngapudaw'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC019', 'name' => 'Nyaungdon'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC020', 'name' => 'Pantanaw'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC021', 'name' => 'Pathein'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC022', 'name' => 'Pyapon'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC023', 'name' => 'Thabaung'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC024', 'name' => 'Wakema'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC025', 'name' => 'Yegyi'],
        //     ['state_id' => 'MMS01', 'id' => 'MMC026', 'name' => 'Zalun'],


        //     // Bago East Division
        //     ['state_id' => 'MMS02', 'id' => 'MMC027', 'name' => 'Bago'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC028', 'name' => 'Daik-U'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC029', 'name' => 'Kawa'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC030', 'name' => 'Kyaukkyi'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC031', 'name' => 'Kyauktaga'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC032', 'name' => 'Nyaunglebin'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC033', 'name' => 'Oktwin'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC034', 'name' => 'Phyu'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC035', 'name' => 'Shwegyin'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC036', 'name' => 'Tantabin'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC037', 'name' => 'Taungoo'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC038', 'name' => 'Thanatpin'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC039', 'name' => 'Waw'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC040', 'name' => 'Yedashe'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC041', 'name' => 'Gyobingauk'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC042', 'name' => 'Letpadan'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC043', 'name' => 'Minhla'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC044', 'name' => 'Monyo'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC045', 'name' => 'Nattalin'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC046', 'name' => 'Okpho'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC047', 'name' => 'Padaung'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC048', 'name' => 'Pauk Kaung'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC049', 'name' => 'Paungde'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC050', 'name' => 'Pyay'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC051', 'name' => 'Shwedaung'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC052', 'name' => 'Thayarwady'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC053', 'name' => 'Thegon'],
        //     ['state_id' => 'MMS02', 'id' => 'MMC054', 'name' => 'Zigon'],

        //     // Chin State
        //     ['state_id' => 'MMS03', 'id' => 'MMC055', 'name' => 'Falam'],
        //     ['state_id' => 'MMS03', 'id' => 'MMC056', 'name' => 'Hakha'],
        //     ['state_id' => 'MMS03', 'id' => 'MMC057', 'name' => 'Htantlang'],
        //     ['state_id' => 'MMS03', 'id' => 'MMC058', 'name' => 'Kanpetlet'],
        //     ['state_id' => 'MMS03', 'id' => 'MMC059', 'name' => 'Madupi'],
        //     ['state_id' => 'MMS03', 'id' => 'MMC060', 'name' => 'Mindat'],
        //     ['state_id' => 'MMS03', 'id' => 'MMC061', 'name' => 'Paletwa'],
        //     ['state_id' => 'MMS03', 'id' => 'MMC062', 'name' => 'Tiddim'],
        //     ['state_id' => 'MMS03', 'id' => 'MMC063', 'name' => 'Tonzang'],

        //     // Kachin State
        //     ['state_id' => 'MMS04', 'id' => 'MMC064', 'name' => 'Bhamo'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC065', 'name' => 'Chipwi'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC066', 'name' => 'Hpakan'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC067', 'name' => 'Injangyang'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC068', 'name' => 'Kawnglanghpu'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC069', 'name' => 'Machanbaw'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC070', 'name' => 'Mansi'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC071', 'name' => 'Mogaung'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC072', 'name' => 'Mohnyin'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC073', 'name' => 'Momauk'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC074', 'name' => 'Myitkyina'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC075', 'name' => 'Nogmung'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC076', 'name' => 'Puta-O'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC077', 'name' => 'Shwegu'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC078', 'name' => 'Sumprabum'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC079', 'name' => 'Tanai'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC080', 'name' => 'Tsawlaw'],
        //     ['state_id' => 'MMS04', 'id' => 'MMC081', 'name' => 'Waingmaw'],

        //     // Kayah State
        //     ['state_id' => 'MMS05', 'id' => 'MMC082', 'name' => 'Bawlakhe'],
        //     ['state_id' => 'MMS05', 'id' => 'MMC083', 'name' => 'Demoso'],
        //     ['state_id' => 'MMS05', 'id' => 'MMC084', 'name' => 'Hpasawng'],
        //     ['state_id' => 'MMS05', 'id' => 'MMC085', 'name' => 'Hpruso'],
        //     ['state_id' => 'MMS05', 'id' => 'MMC086', 'name' => 'Loikaw'],
        //     ['state_id' => 'MMS05', 'id' => 'MMC087', 'name' => 'Mese'],
        //     ['state_id' => 'MMS05', 'id' => 'MMC088', 'name' => 'Shadaw'],

        //     // Kayin State
        //     ['state_id' => 'MMS06', 'id' => 'MMC089', 'name' => 'Hlaingbwe'],
        //     ['state_id' => 'MMS06', 'id' => 'MMC090', 'name' => 'Hpa-An'],
        //     ['state_id' => 'MMS06', 'id' => 'MMC091', 'name' => 'Hpapun'],
        //     ['state_id' => 'MMS06', 'id' => 'MMC092', 'name' => 'Kawkareik'],
        //     ['state_id' => 'MMS06', 'id' => 'MMC093', 'name' => 'Kyain Seikgyi'],
        //     ['state_id' => 'MMS06', 'id' => 'MMC094', 'name' => 'Myawaddy'],
        //     ['state_id' => 'MMS06', 'id' => 'MMC095', 'name' => 'Thandaung'],

        //     // Magway Division
        //     ['state_id' => 'MMS07', 'id' => 'MMC096', 'name' => 'Aunglan'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC097', 'name' => 'Chauk'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC098', 'name' => 'Gangaw'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC099', 'name' => 'Kamma'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC100', 'name' => 'Magway'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC101', 'name' => 'Minbu'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC102', 'name' => 'Mindon'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC103', 'name' => 'Minhla'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC104', 'name' => 'Myaing'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC105', 'name' => 'Myothit'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC106', 'name' => 'Natmauk'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC107', 'name' => 'Ngape'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC108', 'name' => 'Pakokku'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC109', 'name' => 'Pauk'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC110', 'name' => 'Pwintbyu'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC111', 'name' => 'Salin'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC112', 'name' => 'Saw'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC113', 'name' => 'Seikphyu'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC114', 'name' => 'Sidoktaya'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC115', 'name' => 'Sinbaungwe'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC116', 'name' => 'Taungdwingyi'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC117', 'name' => 'Thayet'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC118', 'name' => 'Tilin'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC119', 'name' => 'Yenangyaung'],
        //     ['state_id' => 'MMS07', 'id' => 'MMC120', 'name' => 'Yesagyo'],

        //     // Mandalay Division
        //     ['state_id' => 'MMS08', 'id' => 'MMC121', 'name' => 'Amarapura'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC122', 'name' => 'Aungmyaythazan'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC123', 'name' => 'Chanayethazan'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC124', 'name' => 'Chanmyathazi'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC125', 'name' => 'Kyaukpadaung'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC126', 'name' => 'Kyaukse'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC127', 'name' => 'Lewe'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC128', 'name' => 'Madaya'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC129', 'name' => 'Mahaaungmyay'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC130', 'name' => 'Mahlaing'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC131', 'name' => 'Mandalay'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC132', 'name' => 'Meiktila'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC133', 'name' => 'Mogoke'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC134', 'name' => 'Myingyan'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC135', 'name' => 'Myittha'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC136', 'name' => 'Natogyi'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC137', 'name' => 'Ngazun'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC138', 'name' => 'Nyaung-U'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC139', 'name' => 'Patheingyi'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC140', 'name' => 'Pyawbwe'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC141', 'name' => 'Pyigyitagon'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC142', 'name' => 'Pyinmana'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC143', 'name' => 'Pyinoolwin'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC144', 'name' => 'Singu'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC145', 'name' => 'Sintgaing'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC146', 'name' => 'Tada-U'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC147', 'name' => 'Tatkon'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC148', 'name' => 'Taungtha'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC149', 'name' => 'Thabeikkyin'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC150', 'name' => 'Thazi'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC151', 'name' => 'Wundwin'],
        //     ['state_id' => 'MMS08', 'id' => 'MMC152', 'name' => 'Yamethin'],

        //     // Mon State
        //     ['state_id' => 'MMS09', 'id' => 'MMC153', 'name' => 'Bilin'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC154', 'name' => 'Chaungzon'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC155', 'name' => 'Kyaikmaraw'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC156', 'name' => 'Kyaikto'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC157', 'name' => 'Mawlamyine'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC158', 'name' => 'Mudon'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC159', 'name' => 'Paung'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC160', 'name' => 'Thanbyuzayat'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC161', 'name' => 'Thaton'],
        //     ['state_id' => 'MMS09', 'id' => 'MMC162', 'name' => 'Ye'],

        //     /* Naypitaw U.Territory Region */
        //     ['state_id' => 'MMS10', 'id' => 'MMC163', 'name' => 'Dhatkhina Thiri'],
        //     ['state_id' => 'MMS10', 'id' => 'MMC164', 'name' => 'Lae way'],
        //     ['state_id' => 'MMS10', 'id' => 'MMC165', 'name' => 'Ottara Thiri'],
        //     ['state_id' => 'MMS10', 'id' => 'MMC166', 'name' => 'Pobba Thiri'],
        //     ['state_id' => 'MMS10', 'id' => 'MMC167', 'name' => 'Pyinmana'],
        //     ['state_id' => 'MMS10', 'id' => 'MMC168', 'name' => 'Tatkon'],
        //     ['state_id' => 'MMS10', 'id' => 'MMC169', 'name' => 'Yamethin'],
        //     ['state_id' => 'MMS10', 'id' => 'MMC170', 'name' => 'Zabuthiri'],
        //     ['state_id' => 'MMS10', 'id' => 'MMC171', 'name' => 'Zayar Thiri'],

        //     /* Rakhine State */
        //     ['state_id' => 'MMS11', 'id' => 'MMC172', 'name' => 'Ann'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC173', 'name' => 'Buthidaung'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC174', 'name' => 'Gwa'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC175', 'name' => 'Kyaukpyu'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC176', 'name' => 'Kyauktaw'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC177', 'name' => 'Maungdaw'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC178', 'name' => 'Minbya'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC179', 'name' => 'Mrauk-U'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC180', 'name' => 'Munaung'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC181', 'name' => 'Myebon'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC182', 'name' => 'Pauktaw'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC183', 'name' => 'Ponnagyun'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC184', 'name' => 'Ramree'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC185', 'name' => 'Rathedaung'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC186', 'name' => 'Sittwe'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC189', 'name' => 'Thandwe'],
        //     ['state_id' => 'MMS11', 'id' => 'MMC190', 'name' => 'Toungup'],

        //     // Sagaing Division
        //     ['state_id' => 'MMS12', 'id' => 'MMC191', 'name' => 'Ayadaw'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC192', 'name' => 'Banmauk'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC193', 'name' => 'Budalin'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC194', 'name' => 'Chaung-U'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC195', 'name' => 'Hkamti'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC196', 'name' => 'Homalin'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC197', 'name' => 'Indaw'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC198', 'name' => 'Kale'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC199', 'name' => 'Kalewa'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC200', 'name' => 'kanbalu'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC201', 'name' => 'Kani'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC202', 'name' => 'Katha'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC203', 'name' => 'Kawlin'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC204', 'name' => 'Khin-U'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC205', 'name' => 'Kyunhla'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC206', 'name' => 'Lahe'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC207', 'name' => 'Lay Shi'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC208', 'name' => 'Mawlaik'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC209', 'name' => 'Mingin'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC210', 'name' => 'Monywa'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC211', 'name' => 'Myaung'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC212', 'name' => 'Myinmu'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC213', 'name' => 'Nanyun'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC214', 'name' => 'Pale'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC215', 'name' => 'Paungbyin'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC216', 'name' => 'Pinlebu'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC217', 'name' => 'Sagaing'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC218', 'name' => 'Salingyi'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC219', 'name' => 'Shwebo'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC220', 'name' => 'Tabayin'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC221', 'name' => 'Tamu'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC222', 'name' => 'Taze'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC223', 'name' => 'Tigyaing'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC224', 'name' => 'Wetlet'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC225', 'name' => 'Wuntho'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC226', 'name' => 'Ye-U'],
        //     ['state_id' => 'MMS12', 'id' => 'MMC227', 'name' => 'Yinmabin'],

        //     // Shan State (East)
        //     ['state_id' => 'MMS13', 'id' => 'MMC228', 'name' => 'Kengtung'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC229', 'name' => 'Matman'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC230', 'name' => 'Monghpyak'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC231', 'name' => 'Monghsat'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC232', 'name' => 'Mongkhet'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC233', 'name' => 'Mongla'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC234', 'name' => 'Mongping'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC235', 'name' => 'Mongton'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC236', 'name' => 'Mongyang'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC237', 'name' => 'Mongyawng'],
        //     ['state_id' => 'MMS13', 'id' => 'MMC238', 'name' => 'Tachileik'],

        //     // Shan State (North)
        //     ['state_id' => 'MMS14', 'id' => 'MMC239', 'name' => 'Hopang'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC240', 'name' => 'Hseni'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC241', 'name' => 'Hsipaw'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC242', 'name' => 'Konkyan'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC243', 'name' => 'Kunlong'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC244', 'name' => 'Kutkai'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC245', 'name' => 'Kyuakme'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC246', 'name' => 'Lashio'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC247', 'name' => 'Laukkaing'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC248', 'name' => 'Mabein'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC249', 'name' => 'Manton'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC250', 'name' => 'Mongmao'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC251', 'name' => 'Mongmit'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC252', 'name' => 'Mongyai'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC253', 'name' => 'Muse'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC254', 'name' => 'Namhsan'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC255', 'name' => 'Namphan'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC256', 'name' => 'Namtu'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC257', 'name' => 'Nanhkan'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC258', 'name' => 'Nawnghkio'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC259', 'name' => 'Pangsang'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC260', 'name' => 'Pangwaun'],
        //     ['state_id' => 'MMS14', 'id' => 'MMC261', 'name' => 'Tangyan'],

        //     // Shan State (South)
        //     ['state_id' => 'MMS15', 'id' => 'MMC262', 'name' => 'Hopong'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC263', 'name' => 'Hsihseng'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC264', 'name' => 'Kalaw'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC265', 'name' => 'Kunhing'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC266', 'name' => 'Kyethi'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC267', 'name' => 'Laihka'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC268', 'name' => 'Langkho'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC269', 'name' => 'Lawksawk'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC270', 'name' => 'Loilen'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC271', 'name' => 'Mawkmai'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC272', 'name' => 'Monghsu'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC273', 'name' => 'Mongkaung'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC274', 'name' => 'Mongnai'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC275', 'name' => 'Mongpan'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC276', 'name' => 'Nansang'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC277', 'name' => 'Nyaungshwe'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC278', 'name' => 'Pekon'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC279', 'name' => 'Pindaya'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC280', 'name' => 'Pinlaung'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC281', 'name' => 'Taunggyi'],
        //     ['state_id' => 'MMS15', 'id' => 'MMC282', 'name' => 'Ywangan'],

        //     // Tanintharyi Division
        //     ['state_id' => 'MMS16', 'id' => 'MMC283', 'name' => 'Bokpyin'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC284', 'name' => 'Dawei'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC285', 'name' => 'Kawthoung'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC286', 'name' => 'Kyunsu'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC287', 'name' => 'Launglon'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC288', 'name' => 'Myeik'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC289', 'name' => 'Palaw'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC290', 'name' => 'Tanintharyi'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC291', 'name' => 'Thayetchaung'],
        //     ['state_id' => 'MMS16', 'id' => 'MMC292', 'name' => 'Yebyu'],

        //     ['state_id' => 'MMS17', 'id' => 'MMC293', 'name' => 'Dagon Myothit'],
        //     ['state_id' => 'MMS17', 'id' => 'MMC294', 'name' => 'Yangon City'],
        //     ['state_id' => 'MMS17', 'id' => 'MMC295', 'name' => 'Yangon Division'],
        // ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cities');
    }
}